import React from 'react'
import FloatingImages from '../Components/Landing/Landingbackground'
import GlassEffectBg from '../Components/Landing/GlassEffectBg'
import MainContentArea from '../Components/Landing/MainContentArea'

const LandingPage = () => {
  // Create array of chemistry images with varying durations
  const chemistryImages = [
    { src: '/chemistry.png', duration: 20 },
    { src: '/chemistry1.png', duration: 24 },
    { src: '/chemistry2.png', duration: 28 },
    { src: '/chemistry3.png', duration: 22 },
    { src: '/chemistry4.png', duration: 26 },
    { src: '/chemistry5.png', duration: 30 },
    { src: '/chemistry6.png', duration: 25 },
    { src: '/chemistry7.png', duration: 23 },
    { src: '/chemistry.png', duration: 20 },
    { src: '/chemistry1.png', duration: 24 },
    { src: '/chemistry2.png', duration: 28 },
    { src: '/chemistry3.png', duration: 22 },
    { src: '/chemistry4.png', duration: 26 },
    { src: '/chemistry5.png', duration: 30 },
    { src: '/chemistry6.png', duration: 25 },
    { src: '/chemistry7.png', duration: 23 },
    { src: '/chemistry.png', duration: 20 },
    { src: '/chemistry1.png', duration: 24 },
    { src: '/chemistry2.png', duration: 28 },
    { src: '/chemistry3.png', duration: 22 },
    { src: '/chemistry4.png', duration: 26 },
    { src: '/chemistry5.png', duration: 30 },
    { src: '/chemistry6.png', duration: 25 },
    { src: '/chemistry7.png', duration: 23 },
    { src: '/chemistry.png', duration: 20 },
    { src: '/chemistry1.png', duration: 24 },
    { src: '/chemistry2.png', duration: 28 },
    { src: '/chemistry3.png', duration: 22 },
    { src: '/chemistry4.png', duration: 26 },
    { src: '/chemistry5.png', duration: 30 },
    { src: '/chemistry6.png', duration: 25 },
    { src: '/chemistry7.png', duration: 23 },
    { src: '/chemistry.png', duration: 20 },
    { src: '/chemistry1.png', duration: 24 },
    { src: '/chemistry2.png', duration: 28 },
    { src: '/chemistry3.png', duration: 22 },
    { src: '/chemistry4.png', duration: 26 },
    { src: '/chemistry5.png', duration: 30 },
    { src: '/chemistry6.png', duration: 25 },
    { src: '/chemistry7.png', duration: 23 },
    { src: '/chemistry.png', duration: 20 },
    { src: '/chemistry1.png', duration: 24 },
    { src: '/chemistry2.png', duration: 28 },
    { src: '/chemistry3.png', duration: 22 },
    { src: '/chemistry4.png', duration: 26 },
    { src: '/chemistry5.png', duration: 30 },
    { src: '/chemistry6.png', duration: 25 },
    { src: '/chemistry7.png', duration: 23 },
    { src: '/chemistry.png', duration: 20 },
    { src: '/chemistry1.png', duration: 24 },
    { src: '/chemistry2.png', duration: 28 },
    { src: '/chemistry3.png', duration: 22 },
    { src: '/chemistry4.png', duration: 26 },
    { src: '/chemistry5.png', duration: 30 },
    { src: '/chemistry6.png', duration: 25 },
    { src: '/chemistry7.png', duration: 23 },
    { src: '/chemistry.png', duration: 20 },
    { src: '/chemistry1.png', duration: 24 },
    { src: '/chemistry2.png', duration: 28 },
    { src: '/chemistry3.png', duration: 22 },
    { src: '/chemistry4.png', duration: 26 },
    { src: '/chemistry5.png', duration: 30 },
    { src: '/chemistry6.png', duration: 25 },
    { src: '/chemistry7.png', duration: 23 },
    { src: '/chemistry.png', duration: 20 },
    { src: '/chemistry1.png', duration: 24 },
    { src: '/chemistry2.png', duration: 28 },
    { src: '/chemistry3.png', duration: 22 },
    { src: '/chemistry4.png', duration: 26 },
    { src: '/chemistry5.png', duration: 30 },
    { src: '/chemistry6.png', duration: 25 },
    { src: '/chemistry7.png', duration: 23 },
    { src: '/chemistry.png', duration: 20 },
    { src: '/chemistry1.png', duration: 24 },
    { src: '/chemistry2.png', duration: 28 },
    { src: '/chemistry3.png', duration: 22 },
    { src: '/chemistry4.png', duration: 26 },
    { src: '/chemistry5.png', duration: 30 },
    { src: '/chemistry6.png', duration: 25 },
    { src: '/chemistry7.png', duration: 23 },
    { src: '/chemistry.png', duration: 20 },
    { src: '/chemistry1.png', duration: 24 },
    { src: '/chemistry2.png', duration: 28 },
    { src: '/chemistry3.png', duration: 22 },
    { src: '/chemistry4.png', duration: 26 },
    { src: '/chemistry5.png', duration: 30 },
    { src: '/chemistry6.png', duration: 25 },
    { src: '/chemistry7.png', duration: 23 },
    { src: '/chemistry.png', duration: 20 },
    { src: '/chemistry1.png', duration: 24 },
    { src: '/chemistry2.png', duration: 28 },
    { src: '/chemistry3.png', duration: 22 },
    { src: '/chemistry4.png', duration: 26 },
    { src: '/chemistry5.png', duration: 30 },
    { src: '/chemistry6.png', duration: 25 },
    { src: '/chemistry7.png', duration: 23 },
    { src: '/chemistry.png', duration: 20 },
    { src: '/chemistry1.png', duration: 24 },
    { src: '/chemistry2.png', duration: 28 },
    { src: '/chemistry3.png', duration: 22 },
    { src: '/chemistry4.png', duration: 26 },
    { src: '/chemistry5.png', duration: 30 },
    { src: '/chemistry6.png', duration: 25 },
    { src: '/chemistry7.png', duration: 23 },
    { src: '/chemistry.png', duration: 20 },
    { src: '/chemistry1.png', duration: 24 },
    { src: '/chemistry2.png', duration: 28 },
    { src: '/chemistry3.png', duration: 22 },
    { src: '/chemistry4.png', duration: 26 },
    { src: '/chemistry5.png', duration: 30 },
    { src: '/chemistry6.png', duration: 25 },
    { src: '/chemistry7.png', duration: 23 },
    { src: '/chemistry.png', duration: 20 },
    { src: '/chemistry1.png', duration: 24 },
    { src: '/chemistry2.png', duration: 28 },
    { src: '/chemistry3.png', duration: 22 },
    { src: '/chemistry4.png', duration: 26 },
    { src: '/chemistry5.png', duration: 30 },
    { src: '/chemistry6.png', duration: 25 },
    { src: '/chemistry7.png', duration: 23 },
    { src: '/chemistry.png', duration: 20 },
    { src: '/chemistry1.png', duration: 24 },
    { src: '/chemistry2.png', duration: 28 },
    { src: '/chemistry3.png', duration: 22 },
    { src: '/chemistry4.png', duration: 26 },
    { src: '/chemistry5.png', duration: 30 },
    { src: '/chemistry6.png', duration: 25 },
    { src: '/chemistry7.png', duration: 23 }
  ];

  return (
    <div className='bg-gray-300 min-h-screen w-screen relative'>
      {/* Floating images below glass effect */}
      <div className="absolute inset-0 z-0">
        <FloatingImages images={chemistryImages} />
      </div>
      {/* Glass effect above floating images */}
      <div className="absolute inset-0 z-10 pointer-events-none">
        <GlassEffectBg />
      </div>

      {/* Main content area */}
      <MainContentArea />
    </div>
  )
}

export default LandingPage